#### Parameter file

# Values in this section are substituted into the other sections
# The simulation name (box size and resolution) and snapshot will be appended
# to these to get the full name of the input/output files/directories
Parameters:
  sim_dir: ../
  scratch_dir: ./
  output_dir: ./
# Location of the Swift snapshots:
Snapshots:
  # Use {snap_nr:04d} for the snapshot number and {file_nr} for the file number.
  filename: "{sim_dir}/m12i_cdmo_{snap_nr:04d}.hdf5"

# Which halo finder we're using, and base name for halo finder output files
HaloFinder:
  type: HBTplus
  filename: "{sim_dir}/hbtplus_min_20/{snap_nr:03d}/SubSnap_{snap_nr:03d}"
  fof_filename: "{sim_dir}/fof_min_20/fof_min_20_{snap_nr:04d}.hdf5"

GroupMembership:
  # Where to write the group membership files
  filename: "{output_dir}/SOAP_uncompressed/membership_{snap_nr:04d}.hdf5"

HaloProperties:
  # Where to write the halo properties file
  filename: "{output_dir}/SOAP_uncompressed/halo_properties_{snap_nr:04d}.hdf5"
  # Where to write temporary chunk output
  chunk_dir: "{scratch_dir}/SOAP-tmp/{halo_finder}/"

ApertureProperties:
  properties:
    {}
  variations:
    {}
ProjectedApertureProperties:
  properties:
    {}
  variations:
    {}
SOProperties:
  properties:
    CentreOfMass: true
    CentreOfMassVelocity: true
    Concentration: true
    ConcentrationSoft: true
    DarkMatterMass: true
    DarkMatterConcentration: true
    DarkMatterConcentrationUnsoftened: true
    MassFractionSatellites: true
    MassFractionExternal: true
    NumberOfDarkMatterParticles: true
    SORadius: true
    SpinParameter: true
    TotalMass: true
  variations:
    200_crit:
      type: crit
      value: 200.0
    200_mean:
      type: mean
      value: 200.0
    50_crit:
      type: crit
      value: 50.0
    100_crit:
      type: crit
      value: 100.0
    BN98:
      type: BN98
      value: 0.0
SubhaloProperties:
  properties:
    CentreOfMass: true
    CentreOfMassVelocity: true
    DarkMatterMass: true
    HalfMassRadiusBaryons: true
    HalfMassRadiusDarkMatter: true
    HalfMassRadiusGas: true
    HalfMassRadiusStars: true
    HalfMassRadiusTotal: true
    EncloseRadius: true
    MaximumCircularVelocity: true
    MaximumCircularVelocityRadiusUnsoftened: true
    MaximumCircularVelocityUnsoftened: true
    MaximumDarkMatterCircularVelocity: true
    MaximumDarkMatterCircularVelocityRadius: true
    NumberOfDarkMatterParticles: true
    MaximumCircularVelocity: true
    MaximumCircularVelocitySoft: true
    MaximumCircularVelocityRadius: true
    SpinParameter: true
    TotalMass: true
  variations:
    Bound:
      bound_only: true

filters:
  general:
    limit: 20
    properties:
      - BoundSubhalo/NumberOfGasParticles
      - BoundSubhalo/NumberOfDarkMatterParticles
      - BoundSubhalo/NumberOfStarParticles
      - BoundSubhalo/NumberOfBlackHoleParticles
    combine_properties: sum
  dm:
    limit: 20
    properties:
      - BoundSubhalo/NumberOfDarkMatterParticles
calculations:
  recalculate_xrays: false
  calculate_missing_properties: false
  min_read_radius_cmpc: 5
  recently_heated_gas_filter:
    delta_time_myr: 15
    use_AGN_delta_T: true